export const eventsJsonLd = [
  {
    '@context': 'https://schema.org',
    '@type': 'MusicEvent',
    name: 'Small Party — Small Records × Panic Room',
    startDate: '2026-09-11T22:00:00+02:00',
    endDate: '2026-09-12T05:00:00+02:00',
    eventStatus: 'https://schema.org/EventScheduled',
    eventAttendanceMode: 'https://schema.org/OfflineEventAttendanceMode',
    url: 'https://small-records.com/events/',
    isAccessibleForFree: true,
    location: {
      '@type': 'Place',
      name: 'Panic Room',
      address: {
        '@type': 'PostalAddress',
        streetAddress: '101 rue Amelot',
        postalCode: '75011',
        addressLocality: 'Paris',
        addressCountry: 'FR',
      },
    },
    performer: [
      { '@type': 'Person', name: 'Lessovik' },
      { '@type': 'Person', name: 'Casæ' },
      { '@type': 'Person', name: 'Momal' },
      { '@type': 'Person', name: 'Letché' },
    ],
    organizer: { '@type': 'Organization', name: 'Small Records', url: 'https://small-records.com' },
    image: 'https://small-records.com/images/panic-room/trio.jpg',
  },
  {
    '@context': 'https://schema.org',
    '@type': 'MusicEvent',
    name: 'Early Reflections × Small Records — Gambetta Club',
    startDate: '2026-04-30T22:00:00+02:00',
    endDate: '2026-05-01T06:00:00+02:00',
    eventStatus: 'https://schema.org/EventScheduled',
    eventAttendanceMode: 'https://schema.org/OfflineEventAttendanceMode',
    url: 'https://small-records.com/events/',
    location: {
      '@type': 'Place',
      name: 'Le Gambetta Club',
      address: {
        '@type': 'PostalAddress',
        streetAddress: '104 rue de Bagnolet',
        postalCode: '75020',
        addressLocality: 'Paris',
        addressCountry: 'FR',
      },
    },
    performer: [
      { '@type': 'Person', name: 'Letche' },
      { '@type': 'Person', name: 'Casæ' },
      { '@type': 'Person', name: 'DDG' },
      { '@type': 'Person', name: 'Zeko' },
      { '@type': 'Person', name: 'Copac' },
      { '@type': 'Person', name: 'Scott Civil' },
      { '@type': 'Person', name: 'Momal' },
    ],
    organizer: [
      { '@type': 'Organization', name: 'Early Reflections' },
      { '@type': 'Organization', name: 'Small Records', url: 'https://small-records.com' },
    ],
    image: 'https://small-records.com/images/early-reflection/packed-room.jpg',
  },
]
